name: Docker Build & Push and Deploy to podspace-server

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Read Docker Image Identifiers
        id: read-docker-image-identifiers
        run: echo ::set-env name=IMAGE_REPOSITORY::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')

      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest

      - name: Remote SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: deployer
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo ${{ secrets.ENV_PRODUCTION }} | base64 --decode > .env.production-${{ secrets.POD_NUMBER }}
            docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
            docker container rm -f podspace-${{ secrets.POD_NUMBER }} || true
            docker run --env-file .env.production-${{ secrets.POD_NUMBER }} -d -p ${{ secrets.SERVER_PORT }}:8080 --restart on-failure --name=podspace-${{ secrets.POD_NUMBER }} ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
            rm .env.production-${{ secrets.POD_NUMBER }}
